### ISSUE TITLE
AttributeError: module 'string' has no attribute 'strip'

### ISSUE THREAD

**Issue by DanielBonnery** [kjellmf/svg2tikz#37]
I downloaded [rstudio.svg](https://rviews.rstudio.com/css/images/rstudio.svg), installed svg2tikz, and tried to convert the file to tikz.
//

I ran:

```
wget https://rviews.rstudio.com/css/images/rstudio.svg
pip install git+git://github.com/kjellmf/svg2tikz --user
svg2tikz --figonly rstudio.svg
```

I got

```
Traceback (most recent call last):
  File "/home/XXXX/.local/bin/svg2tikz", line 11, in <module>
    sys.exit(main_cmdline())
  File "/home/XXXX/.local/lib/python3.5/site-packages/svg2tikz/extensions/tikz_export.py", line 1433, in main_cmdline
    tikz_code = effect.convert(svg_file=None, cmd_line_mode=True, **kwargs)
  File "/home/XXXX/.local/lib/python3.5/site-packages/svg2tikz/extensions/tikz_export.py", line 1390, in convert
    output = self.effect()
  File "/home/XXXX/.local/lib/python3.5/site-packages/svg2tikz/extensions/tikz_export.py", line 1317, in effect
    graphics_state = GraphicsState(nodes)
  File "/home/XXXX/.local/lib/python3.5/site-packages/svg2tikz/extensions/tikz_export.py", line 537, in __init__
    self._get_graphics_state(svg_node)
  File "/home/XXXX/.local/lib/python3.5/site-packages/svg2tikz/extensions/tikz_export.py", line 543, in _get_graphics_state
    style = parse_style(node.get('style', ''))
  File "/home/XXXX/.local/lib/python3.5/site-packages/svg2tikz/extensions/tikz_export.py", line 514, in parse_style
    return dict([list(map(string.strip, i.split(":"))) for i in s.split(";") if len(i)])
  File "/home/XXXX/.local/lib/python3.5/site-packages/svg2tikz/extensions/tikz_export.py", line 514, in <listcomp>
    return dict([list(map(string.strip, i.split(":"))) for i in s.split(";") if len(i)])
AttributeError: module 'string' has no attribute 'strip'
```

So I did 
```
pip3 uninstall svg2tikz
wget https://rviews.rstudio.com/css/images/rstudio.svg
pip install git+git://github.com/kjellmf/svg2tikz --user
svg2tikz --figonly rstudio.svg
```
and it worked !
It would be nice to do the pull request.

**Comment by kjellmf** [comment]
Works in current master branch.
